services:
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ticket_storage:/app/ticket_storage
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "postgres", "-d", "db-turbanscy-mandaty"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  ticket_storage:
  postgres_data:
