import { Payment } from "./test-columns";

export const MOCK_PAYMENTS: Payment[] = [
  {
    id: 1,
    status: "success",
    amount: 125,
    email: "kdeegan0@guardian.co.uk",
  },
  {
    id: 2,
    status: "pending",
    amount: 22,
    email: "manand1@cdc.gov",
  },
  {
    id: 3,
    status: "pending",
    amount: 813,
    email: "celkins2@bizjournals.com",
  },
  {
    id: 4,
    status: "failed",
    amount: 768,
    email: "bgrahlman3@answers.com",
  },
  {
    id: 5,
    status: "success",
    amount: 181,
    email: "rberanek4@businessweek.com",
  },
  {
    id: 6,
    status: "processing",
    amount: 830,
    email: "ggleeton5@dell.com",
  },
  {
    id: 7,
    status: "processing",
    amount: 721,
    email: "ldinnage6@quantcast.com",
  },
  {
    id: 8,
    status: "success",
    amount: 586,
    email: "mcoopper7@go.com",
  },
  {
    id: 9,
    status: "processing",
    amount: 400,
    email: "ujaycocks8@samsung.com",
  },
  {
    id: 10,
    status: "processing",
    amount: 327,
    email: "mwiddop9@myspace.com",
  },
  {
    id: 11,
    status: "failed",
    amount: 678,
    email: "sfullagara@house.gov",
  },
  {
    id: 12,
    status: "pending",
    amount: 630,
    email: "cneedb@spiegel.de",
  },
  {
    id: 13,
    status: "processing",
    amount: 243,
    email: "hhulburdc@ask.com",
  },
  {
    id: 14,
    status: "pending",
    amount: 995,
    email: "fphoebed@home.pl",
  },
  {
    id: 15,
    status: "success",
    amount: 900,
    email: "riiannonee@webs.com",
  },
  {
    id: 16,
    status: "failed",
    amount: 669,
    email: "eurenf@utexas.edu",
  },
  {
    id: 17,
    status: "processing",
    amount: 179,
    email: "cparkhouseg@sphinn.com",
  },
  {
    id: 18,
    status: "processing",
    amount: 181,
    email: "dmcinilityh@washington.edu",
  },
  {
    id: 19,
    status: "pending",
    amount: 162,
    email: "vboynesi@prnewswire.com",
  },
  {
    id: 20,
    status: "pending",
    amount: 62,
    email: "kvansonj@china.com.cn",
  },
  {
    id: 21,
    status: "failed",
    amount: 705,
    email: "mruskek@pen.io",
  },
  {
    id: 22,
    status: "processing",
    amount: 733,
    email: "fdullinghaml@squarespace.com",
  },
  {
    id: 23,
    status: "processing",
    amount: 424,
    email: "aonoulanem@printfriendly.com",
  },
  {
    id: 24,
    status: "processing",
    amount: 562,
    email: "rskarmann@wsj.com",
  },
  {
    id: 25,
    status: "failed",
    amount: 69,
    email: "edickmano@china.com.cn",
  },
  {
    id: 26,
    status: "success",
    amount: 68,
    email: "ehunnaballp@scientificamerican.com",
  },
  {
    id: 27,
    status: "pending",
    amount: 256,
    email: "yarrigoq@mtv.com",
  },
  {
    id: 28,
    status: "processing",
    amount: 427,
    email: "lseeryr@drupal.org",
  },
  {
    id: 29,
    status: "pending",
    amount: 344,
    email: "ehearleys@technorati.com",
  },
  {
    id: 30,
    status: "pending",
    amount: 909,
    email: "nmcgallt@icq.com",
  },
  {
    id: 31,
    status: "processing",
    amount: 383,
    email: "dsewardu@rediff.com",
  },
  {
    id: 32,
    status: "processing",
    amount: 115,
    email: "lfranckv@about.com",
  },
  {
    id: 33,
    status: "processing",
    amount: 787,
    email: "kcharrissonw@jigsy.com",
  },
  {
    id: 34,
    status: "failed",
    amount: 109,
    email: "bstrattenx@omniture.com",
  },
  {
    id: 35,
    status: "failed",
    amount: 697,
    email: "acardingy@usa.gov",
  },
  {
    id: 36,
    status: "failed",
    amount: 980,
    email: "mmakerz@usnews.com",
  },
  {
    id: 37,
    status: "processing",
    amount: 578,
    email: "astapele10@baidu.com",
  },
  {
    id: 38,
    status: "success",
    amount: 938,
    email: "tclaus11@mysql.com",
  },
  {
    id: 39,
    status: "failed",
    amount: 529,
    email: "osalling12@nasa.gov",
  },
  {
    id: 40,
    status: "processing",
    amount: 24,
    email: "jhollyland13@tripod.com",
  },
  {
    id: 41,
    status: "pending",
    amount: 351,
    email: "iquickenden14@admin.ch",
  },
  {
    id: 42,
    status: "failed",
    amount: 378,
    email: "pkenrick15@ifeng.com",
  },
  {
    id: 43,
    status: "failed",
    amount: 887,
    email: "gesom16@rakuten.co.jp",
  },
  {
    id: 44,
    status: "processing",
    amount: 204,
    email: "tmarzelli17@disqus.com",
  },
  {
    id: 45,
    status: "processing",
    amount: 770,
    email: "crainbow18@alexa.com",
  },
  {
    id: 46,
    status: "processing",
    amount: 44,
    email: "dbullion19@tripadvisor.com",
  },
  {
    id: 47,
    status: "failed",
    amount: 700,
    email: "dwickardt1a@shutterfly.com",
  },
  {
    id: 48,
    status: "processing",
    amount: 867,
    email: "egogerty1b@mysql.com",
  },
  {
    id: 49,
    status: "failed",
    amount: 817,
    email: "jkillbey1c@wunderground.com",
  },
  {
    id: 50,
    status: "success",
    amount: 640,
    email: "mcastello1d@pinterest.com",
  },
  {
    id: 51,
    status: "success",
    amount: 394,
    email: "cdalla1e@epa.gov",
  },
  {
    id: 52,
    status: "success",
    amount: 424,
    email: "hdunridge1f@chicagotribune.com",
  },
  {
    id: 53,
    status: "success",
    amount: 656,
    email: "glagadu1g@weibo.com",
  },
  {
    id: 54,
    status: "success",
    amount: 676,
    email: "ltapper1h@flavors.me",
  },
  {
    id: 55,
    status: "success",
    amount: 867,
    email: "itidmas1i@sphinn.com",
  },
  {
    id: 56,
    status: "pending",
    amount: 286,
    email: "cdedenham1j@dion.ne.jp",
  },
  {
    id: 57,
    status: "success",
    amount: 428,
    email: "bcarradice1k@amazon.de",
  },
  {
    id: 58,
    status: "processing",
    amount: 980,
    email: "awickwar1l@hexun.com",
  },
  {
    id: 59,
    status: "failed",
    amount: 623,
    email: "dmordan1m@umich.edu",
  },
  {
    id: 60,
    status: "failed",
    amount: 553,
    email: "mbalazot1n@tuttocitta.it",
  },
  {
    id: 61,
    status: "failed",
    amount: 659,
    email: "mstrognell1o@washington.edu",
  },
  {
    id: 62,
    status: "failed",
    amount: 395,
    email: "drayworth1p@hatena.ne.jp",
  },
  {
    id: 63,
    status: "processing",
    amount: 19,
    email: "mizatt1q@hugedomains.com",
  },
  {
    id: 64,
    status: "success",
    amount: 223,
    email: "iswenson1r@cmu.edu",
  },
  {
    id: 65,
    status: "pending",
    amount: 643,
    email: "dharlowe1s@uol.com.br",
  },
  {
    id: 66,
    status: "processing",
    amount: 655,
    email: "tcarp1t@mac.com",
  },
  {
    id: 67,
    status: "success",
    amount: 112,
    email: "cgodden1u@youtu.be",
  },
  {
    id: 68,
    status: "success",
    amount: 487,
    email: "wdimitru1v@zimbio.com",
  },
  {
    id: 69,
    status: "processing",
    amount: 287,
    email: "cwallwork1w@wix.com",
  },
  {
    id: 70,
    status: "pending",
    amount: 802,
    email: "rgaspard1x@craigslist.org",
  },
  {
    id: 71,
    status: "success",
    amount: 786,
    email: "rouldred1y@51.la",
  },
  {
    id: 72,
    status: "success",
    amount: 943,
    email: "mcolisbe1z@ning.com",
  },
  {
    id: 73,
    status: "pending",
    amount: 810,
    email: "hmcpake20@macromedia.com",
  },
  {
    id: 74,
    status: "processing",
    amount: 968,
    email: "rmacturlough21@nymag.com",
  },
  {
    id: 75,
    status: "success",
    amount: 168,
    email: "lchomicz22@nhs.uk",
  },
  {
    id: 76,
    status: "pending",
    amount: 729,
    email: "trabb23@w3.org",
  },
  {
    id: 77,
    status: "pending",
    amount: 599,
    email: "sahmed24@hostgator.com",
  },
  {
    id: 78,
    status: "pending",
    amount: 493,
    email: "fghelardi25@plala.or.jp",
  },
  {
    id: 79,
    status: "processing",
    amount: 2,
    email: "jhush26@cbsnews.com",
  },
  {
    id: 80,
    status: "success",
    amount: 418,
    email: "mandreasson27@sakura.ne.jp",
  },
  {
    id: 81,
    status: "failed",
    amount: 101,
    email: "cbiddlestone28@scientificamerican.com",
  },
  {
    id: 82,
    status: "pending",
    amount: 574,
    email: "ppegden29@tumblr.com",
  },
  {
    id: 83,
    status: "success",
    amount: 944,
    email: "fwhanstall2a@wsj.com",
  },
  {
    id: 84,
    status: "failed",
    amount: 14,
    email: "ldye2b@ucsd.edu",
  },
  {
    id: 85,
    status: "failed",
    amount: 723,
    email: "idover2c@purevolume.com",
  },
  {
    id: 86,
    status: "success",
    amount: 915,
    email: "pkynsey2d@loc.gov",
  },
  {
    id: 87,
    status: "pending",
    amount: 300,
    email: "fklageman2e@dion.ne.jp",
  },
  {
    id: 88,
    status: "processing",
    amount: 630,
    email: "dstatersfield2f@hostgator.com",
  },
  {
    id: 89,
    status: "processing",
    amount: 703,
    email: "itubb2g@amazon.com",
  },
  {
    id: 90,
    status: "processing",
    amount: 490,
    email: "msoro2h@goo.ne.jp",
  },
  {
    id: 91,
    status: "processing",
    amount: 286,
    email: "epaynter2i@unesco.org",
  },
  {
    id: 92,
    status: "pending",
    amount: 63,
    email: "zcaldroni2j@home.pl",
  },
  {
    id: 93,
    status: "success",
    amount: 618,
    email: "blye2k@cbc.ca",
  },
  {
    id: 94,
    status: "processing",
    amount: 603,
    email: "tpietzke2l@clickbank.net",
  },
  {
    id: 95,
    status: "processing",
    amount: 383,
    email: "ckeeri2m@diigo.com",
  },
  {
    id: 96,
    status: "processing",
    amount: 320,
    email: "tcolvine2n@fda.gov",
  },
  {
    id: 97,
    status: "processing",
    amount: 919,
    email: "aharford2o@nytimes.com",
  },
  {
    id: 98,
    status: "success",
    amount: 641,
    email: "jbuscombe2p@icio.us",
  },
  {
    id: 99,
    status: "failed",
    amount: 509,
    email: "btoffoloni2q@youku.com",
  },
  {
    id: 100,
    status: "pending",
    amount: 502,
    email: "wlangelaan2r@yelp.com",
  },
];
