import { Payment } from "./test-columns";

export const MOCK_PAYMENTS: Payment[] = [
  {
    id: 1,
    status: "Pending",
    amount: 162,
    date: "cze 25, 2024",
    email: "aortet0@yelp.com",
  },
  {
    id: 2,
    status: "Success",
    amount: 556,
    date: "lip 1, 2024",
    email: "jduplain1@dailymail.co.uk",
  },
  {
    id: 3,
    status: "Failed",
    amount: 144,
    date: "cze 30, 2024",
    email: "pamsberger2@wikipedia.org",
  },
  {
    id: 4,
    status: "Success",
    amount: 121,
    date: "may 3, 2024",
    email: "waleksahkin3@harvard.edu",
  },
  {
    id: 5,
    status: "Success",
    amount: 22,
    date: "may 5, 2024",
    email: "csalisbury4@ucla.edu",
  },
  {
    id: 6,
    status: "Pending",
    amount: 88,
    date: "may 5, 2024",
    email: "atrewhella5@harvard.edu",
  },
  {
    id: 7,
    status: "Failed",
    amount: 790,
    date: "lip 3, 2024",
    email: "fpie6@bloomberg.com",
  },
  {
    id: 8,
    status: "Failed",
    amount: 549,
    date: "lip 4, 2024",
    email: "jstefi7@hatena.ne.jp",
  },
  {
    id: 9,
    status: "Failed",
    amount: 448,
    date: "may 30, 2024",
    email: "tgrangier8@hatena.ne.jp",
  },
  {
    id: 10,
    status: "Processing",
    amount: 441,
    date: "cze 30, 2024",
    email: "gcowndley9@bizjournals.com",
  },
  {
    id: 11,
    status: "Processing",
    amount: 432,
    date: "lip 3, 2024",
    email: "vwormana@4shared.com",
  },
  {
    id: 12,
    status: "Failed",
    amount: 746,
    date: "sie 6, 2024",
    email: "mjeannonb@gmpg.org",
  },
  {
    id: 13,
    status: "Failed",
    amount: 148,
    date: "cze 30, 2024",
    email: "sritchardc@is.gd",
  },
  {
    id: 14,
    status: "Success",
    amount: 734,
    date: "may 30, 2024",
    email: "rtilted@deviantart.com",
  },
  {
    id: 15,
    status: "Processing",
    amount: 821,
    date: "cze 3, 2024",
    email: "hewingtone@wikimedia.org",
  },
  {
    id: 16,
    status: "Failed",
    amount: 14,
    date: "sie 1, 2024",
    email: "skinchingtonf@freewebs.com",
  },
  {
    id: 17,
    status: "Failed",
    amount: 887,
    date: "sie 11, 2024",
    email: "sblightg@cafepress.com",
  },
  {
    id: 18,
    status: "Processing",
    amount: 997,
    date: "lip 2, 2024",
    email: "mkennanh@cmu.edu",
  },
  {
    id: 19,
    status: "Pending",
    amount: 954,
    date: "sie 5, 2024",
    email: "mkeri@vimeo.com",
  },
  {
    id: 20,
    status: "Processing",
    amount: 375,
    date: "may 2, 2024",
    email: "sricoldj@jimdo.com",
  },
  {
    id: 21,
    status: "Processing",
    amount: 701,
    date: "cze 7, 2024",
    email: "ascholeyk@w3.org",
  },
  {
    id: 22,
    status: "Success",
    amount: 316,
    date: "sie 3, 2024",
    email: "wmcneel@harvard.edu",
  },
  {
    id: 23,
    status: "Processing",
    amount: 713,
    date: "cze 25, 2024",
    email: "akopfm@nba.com",
  },
  {
    id: 24,
    status: "Pending",
    amount: 560,
    date: "may 6, 2024",
    email: "pwaitlandn@scribd.com",
  },
  {
    id: 25,
    status: "Failed",
    amount: 563,
    date: "sie 5, 2024",
    email: "loduaneo@ed.gov",
  },
  {
    id: 26,
    status: "Processing",
    amount: 7,
    date: "cze 1, 2024",
    email: "lmclarenp@liveinternet.ru",
  },
  {
    id: 27,
    status: "Success",
    amount: 640,
    date: "lip 1, 2024",
    email: "sprimeq@ow.ly",
  },
  {
    id: 28,
    status: "Success",
    amount: 244,
    date: "lip 5, 2024",
    email: "eegrer@buzzfeed.com",
  },
  {
    id: 29,
    status: "Processing",
    amount: 57,
    date: "may 23, 2024",
    email: "sskillingss@ow.ly",
  },
  {
    id: 30,
    status: "Processing",
    amount: 770,
    date: "cze 6, 2024",
    email: "hmactimpanyt@odnoklassniki.ru",
  },
  {
    id: 31,
    status: "Pending",
    amount: 947,
    date: "sie 5, 2024",
    email: "dmarslandu@state.tx.us",
  },
  {
    id: 32,
    status: "Pending",
    amount: 435,
    date: "cze 4, 2024",
    email: "bdalgettyv@liveinternet.ru",
  },
  {
    id: 33,
    status: "Failed",
    amount: 340,
    date: "cze 30, 2024",
    email: "civanchinw@yolasite.com",
  },
  {
    id: 34,
    status: "Failed",
    amount: 778,
    date: "sie 3, 2024",
    email: "jgreatorexx@sciencedirect.com",
  },
  {
    id: 35,
    status: "Processing",
    amount: 658,
    date: "lip 1, 2024",
    email: "bsakery@nih.gov",
  },
  {
    id: 36,
    status: "Processing",
    amount: 318,
    date: "cze 3, 2024",
    email: "msatchellz@unicef.org",
  },
  {
    id: 37,
    status: "Failed",
    amount: 484,
    date: "lip 30, 2024",
    email: "gattwood10@nationalgeographic.com",
  },
  {
    id: 38,
    status: "Processing",
    amount: 836,
    date: "may 1, 2024",
    email: "troch11@indiegogo.com",
  },
  {
    id: 39,
    status: "Processing",
    amount: 538,
    date: "sie 7, 2024",
    email: "gbeaven12@nymag.com",
  },
  {
    id: 40,
    status: "Success",
    amount: 937,
    date: "cze 30, 2024",
    email: "ceastlake13@slashdot.org",
  },
  {
    id: 41,
    status: "Pending",
    amount: 473,
    date: "may 3, 2024",
    email: "lnormanville14@mysql.com",
  },
  {
    id: 42,
    status: "Success",
    amount: 798,
    date: "lip 2, 2024",
    email: "ischroeder15@nhs.uk",
  },
  {
    id: 43,
    status: "Processing",
    amount: 262,
    date: "sie 2, 2024",
    email: "econnah16@homestead.com",
  },
  {
    id: 44,
    status: "Processing",
    amount: 478,
    date: "may 4, 2024",
    email: "uvlahos17@nih.gov",
  },
  {
    id: 45,
    status: "Success",
    amount: 35,
    date: "sie 3, 2024",
    email: "ihukins18@reuters.com",
  },
  {
    id: 46,
    status: "Processing",
    amount: 947,
    date: "lip 4, 2024",
    email: "gdanilovitch19@pinterest.com",
  },
  {
    id: 47,
    status: "Pending",
    amount: 65,
    date: "sie 7, 2024",
    email: "roager1a@storify.com",
  },
  {
    id: 48,
    status: "Processing",
    amount: 931,
    date: "cze 7, 2024",
    email: "ssteuart1b@nhs.uk",
  },
  {
    id: 49,
    status: "Failed",
    amount: 950,
    date: "cze 7, 2024",
    email: "hgresch1c@google.ca",
  },
  {
    id: 50,
    status: "Success",
    amount: 769,
    date: "sie 7, 2024",
    email: "idelve1d@senate.gov",
  },
  {
    id: 51,
    status: "Pending",
    amount: 985,
    date: "sie 30, 2024",
    email: "tlindemann1e@hubpages.com",
  },
  {
    id: 52,
    status: "Processing",
    amount: 411,
    date: "lip 25, 2024",
    email: "bmuris1f@sciencedirect.com",
  },
  {
    id: 53,
    status: "Failed",
    amount: 281,
    date: "lip 5, 2024",
    email: "lmoakes1g@e-recht24.de",
  },
  {
    id: 54,
    status: "Pending",
    amount: 850,
    date: "may 11, 2024",
    email: "eemberton1h@sohu.com",
  },
  {
    id: 55,
    status: "Success",
    amount: 903,
    date: "sie 30, 2024",
    email: "dpitkethly1i@craigslist.org",
  },
  {
    id: 56,
    status: "Success",
    amount: 846,
    date: "cze 3, 2024",
    email: "sbeedle1j@nifty.com",
  },
  {
    id: 57,
    status: "Pending",
    amount: 844,
    date: "lip 23, 2024",
    email: "jaymes1k@youtu.be",
  },
  {
    id: 58,
    status: "Processing",
    amount: 611,
    date: "lip 25, 2024",
    email: "gkubala1l@bing.com",
  },
  {
    id: 59,
    status: "Processing",
    amount: 605,
    date: "may 2, 2024",
    email: "vdepinna1m@themeforest.net",
  },
  {
    id: 60,
    status: "Success",
    amount: 453,
    date: "may 25, 2024",
    email: "kfleury1n@imgur.com",
  },
  {
    id: 61,
    status: "Success",
    amount: 429,
    date: "cze 6, 2024",
    email: "kpollard1o@sphinn.com",
  },
  {
    id: 62,
    status: "Processing",
    amount: 154,
    date: "lip 7, 2024",
    email: "lwhitta1p@harvard.edu",
  },
  {
    id: 63,
    status: "Pending",
    amount: 185,
    date: "lip 4, 2024",
    email: "nkesterton1q@exblog.jp",
  },
  {
    id: 64,
    status: "Processing",
    amount: 305,
    date: "may 3, 2024",
    email: "bostler1r@springer.com",
  },
  {
    id: 65,
    status: "Failed",
    amount: 490,
    date: "cze 23, 2024",
    email: "zfinney1s@blog.com",
  },
  {
    id: 66,
    status: "Pending",
    amount: 45,
    date: "lip 25, 2024",
    email: "cmanger1t@list-manage.com",
  },
  {
    id: 67,
    status: "Success",
    amount: 218,
    date: "cze 30, 2024",
    email: "cphillippo1u@accuweather.com",
  },
  {
    id: 68,
    status: "Failed",
    amount: 964,
    date: "lip 25, 2024",
    email: "yhadcock1v@symantec.com",
  },
  {
    id: 69,
    status: "Pending",
    amount: 373,
    date: "may 1, 2024",
    email: "elocket1w@auda.org.au",
  },
  {
    id: 70,
    status: "Processing",
    amount: 137,
    date: "sie 30, 2024",
    email: "cchenery1x@wisc.edu",
  },
  {
    id: 71,
    status: "Processing",
    amount: 541,
    date: "lip 6, 2024",
    email: "gjelk1y@cdc.gov",
  },
  {
    id: 72,
    status: "Failed",
    amount: 111,
    date: "cze 11, 2024",
    email: "ywemyss1z@vinaora.com",
  },
  {
    id: 73,
    status: "Success",
    amount: 523,
    date: "may 25, 2024",
    email: "dmawford20@netlog.com",
  },
  {
    id: 74,
    status: "Success",
    amount: 215,
    date: "cze 6, 2024",
    email: "dkohtler21@youku.com",
  },
  {
    id: 75,
    status: "Success",
    amount: 199,
    date: "may 30, 2024",
    email: "lmoberley22@163.com",
  },
  {
    id: 76,
    status: "Failed",
    amount: 377,
    date: "lip 30, 2024",
    email: "tarents23@i2i.jp",
  },
  {
    id: 77,
    status: "Pending",
    amount: 191,
    date: "sie 1, 2024",
    email: "gtavner24@google.com.br",
  },
  {
    id: 78,
    status: "Success",
    amount: 852,
    date: "may 3, 2024",
    email: "fwiggins25@nih.gov",
  },
  {
    id: 79,
    status: "Failed",
    amount: 746,
    date: "lip 30, 2024",
    email: "ecobby26@drupal.org",
  },
  {
    id: 80,
    status: "Pending",
    amount: 512,
    date: "cze 23, 2024",
    email: "lskeldinge27@seesaa.net",
  },
  {
    id: 81,
    status: "Processing",
    amount: 48,
    date: "lip 23, 2024",
    email: "lpuller28@nih.gov",
  },
  {
    id: 82,
    status: "Pending",
    amount: 85,
    date: "lip 3, 2024",
    email: "cscripture29@simplemachines.org",
  },
  {
    id: 83,
    status: "Pending",
    amount: 299,
    date: "cze 30, 2024",
    email: "rschollick2a@google.it",
  },
  {
    id: 84,
    status: "Success",
    amount: 272,
    date: "cze 5, 2024",
    email: "fnore2b@state.tx.us",
  },
  {
    id: 85,
    status: "Processing",
    amount: 957,
    date: "may 6, 2024",
    email: "cbowmen2c@delicious.com",
  },
  {
    id: 86,
    status: "Failed",
    amount: 856,
    date: "cze 11, 2024",
    email: "teastmond2d@discuz.net",
  },
  {
    id: 87,
    status: "Failed",
    amount: 542,
    date: "may 6, 2024",
    email: "mgingles2e@xinhuanet.com",
  },
  {
    id: 88,
    status: "Failed",
    amount: 2,
    date: "cze 30, 2024",
    email: "lpudge2f@hhs.gov",
  },
  {
    id: 89,
    status: "Processing",
    amount: 444,
    date: "may 4, 2024",
    email: "lroome2g@slashdot.org",
  },
  {
    id: 90,
    status: "Processing",
    amount: 679,
    date: "lip 3, 2024",
    email: "sheis2h@nhs.uk",
  },
  {
    id: 91,
    status: "Pending",
    amount: 600,
    date: "may 3, 2024",
    email: "cwaszczyk2i@tripadvisor.com",
  },
  {
    id: 92,
    status: "Success",
    amount: 227,
    date: "may 4, 2024",
    email: "ashelborne2j@wikia.com",
  },
  {
    id: 93,
    status: "Success",
    amount: 667,
    date: "lip 11, 2024",
    email: "cjelf2k@tinyurl.com",
  },
  {
    id: 94,
    status: "Failed",
    amount: 133,
    date: "lip 1, 2024",
    email: "mlawry2l@irs.gov",
  },
  {
    id: 95,
    status: "Processing",
    amount: 450,
    date: "lip 5, 2024",
    email: "gcourtes2m@army.mil",
  },
  {
    id: 96,
    status: "Processing",
    amount: 814,
    date: "may 4, 2024",
    email: "gben2n@amazon.co.jp",
  },
  {
    id: 97,
    status: "Pending",
    amount: 588,
    date: "cze 30, 2024",
    email: "rroote2o@t.co",
  },
  {
    id: 98,
    status: "Processing",
    amount: 898,
    date: "lip 4, 2024",
    email: "wnares2p@fema.gov",
  },
  {
    id: 99,
    status: "Success",
    amount: 489,
    date: "lip 3, 2024",
    email: "gimort2q@oaic.gov.au",
  },
  {
    id: 100,
    status: "Processing",
    amount: 118,
    date: "lip 4, 2024",
    email: "nculbert2r@cnn.com",
  },
];
